export const celebrities = [
    { url: '/assets/celebrities/Al Pacino.jpg', name: 'Al Pacino' },
    { url: '/assets/celebrities/Allison Janney.jpg', name: 'Allison Janney' },
    { url: '/assets/celebrities/Amy Adams.jpg', name: 'Amy Adams' },
    { url: '/assets/celebrities/Anna Kendrick.jpg', name: 'Anna Kendrick' },
    { url: '/assets/celebrities/Bill Murray.jpg', name: 'Bill Murray' },
    { url: '/assets/celebrities/Bill Paxton.jpg', name: 'Bill Paxton' },
    { url: '/assets/celebrities/Bob Hoskins.jpg', name: 'Bob Hoskins' },
    { url: '/assets/celebrities/Brad Pitt.jpeg', name: 'Brad Pitt' },
    { url: '/assets/celebrities/Brendan Fraser.jpg', name: 'Brendan Fraser' },
    { url: '/assets/celebrities/Christian Bale.jpg', name: 'Christian Bale' },
    { url: '/assets/celebrities/Colin Firth.jpg', name: 'Colin Firth' },
    { url: '/assets/celebrities/David Tennant.jpeg', name: 'David Tennant' },
    { url: '/assets/celebrities/Dustin Hoffman.jpg', name: 'Dustin Hoffman' },
    { url: '/assets/celebrities/Ed Helms.jpg', name: 'Ed Helms' },
    { url: '/assets/celebrities/Edward Norton.jpg', name: 'Edward Norton' },
    { url: '/assets/celebrities/Emily Mortimer.jpg', name: 'Emily Mortimer' },
    { url: '/assets/celebrities/Frances McDormand.jpg', name: 'Frances McDormand' },
    { url: '/assets/celebrities/George Clooney.jpg', name: 'George Clooney' },
    { url: '/assets/celebrities/Giovanni Ribisi.jpg', name: 'Giovanni Ribisi' },
    { url: '/assets/celebrities/Greg Kinnear.jpg', name: 'Greg Kinnear' },
    { url: '/assets/celebrities/Heath Ledger.jpg', name: 'Heath Ledger' },
    { url: '/assets/celebrities/Helena Bonham Carter.jpg', name: 'Helena Bonham Carter' },
    { url: '/assets/celebrities/Isla Fisher.jpg', name: 'Isla Fisher' },
    { url: '/assets/celebrities/JK Simmons.jpg', name: 'J.K. Simmons' },
    { url: '/assets/celebrities/James Gandolfini.jpg', name: 'James Gandolfini' },
    { url: '/assets/celebrities/James McAvoy.jpg', name: 'James McAvoy' },
    { url: '/assets/celebrities/James Spader.jpg', name: 'James Spader' },
    { url: '/assets/celebrities/Jason Bateman.jpg', name: 'Jason Bateman' },
    { url: '/assets/celebrities/Jennifer Garner.jpg', name: 'Jennifer Garner' },
    { url: '/assets/celebrities/Jennifer Lawrence.jpg', name: 'Jennifer Lawrence' },
    { url: '/assets/celebrities/Joan Cusack.jpg', name: 'Joan Cusack' },
    { url: '/assets/celebrities/Jodie Foster.jpg', name: 'Jodie Foster' },
    { url: '/assets/celebrities/John Cusack.jpg', name: 'John Cusack' },
    { url: '/assets/celebrities/John Goodman.jpg', name: 'John Goodman' },
    { url: '/assets/celebrities/Jonah Hill.jpg', name: 'Jonah Hill' },
    { url: '/assets/celebrities/Julianne Moore.jpg', name: 'Julianne Moore' },
    { url: '/assets/celebrities/Kate Winslet.jpg', name: 'Kate Winslet ' },
    { url: '/assets/celebrities/Kevin Costner.jpg', name: 'Kevin Costner' },
    { url: '/assets/celebrities/Kevin Spacey.jpg', name: 'Kevin Spacey' },
    { url: '/assets/celebrities/Lorraine Bracco.jpg', name: 'Lorraine Bracco' },
    { url: '/assets/celebrities/Mark Ruffalo.jpg', name: 'Mark Ruffalo' },
    { url: '/assets/celebrities/Mark Wahlberg.jpg', name: 'Mark Wahlberg' },
    { url: '/assets/celebrities/Matthew Macfadyen.jpg', name: 'Matthew Macfadyen' },
    { url: '/assets/celebrities/Maya Rudolph.jpg', name: 'Maya Rudolph' },
    { url: '/assets/celebrities/Meg Ryan.jpg', name: 'Meg Ryan' },
    { url: '/assets/celebrities/Melissa Leo.jpg', name: 'Melissa Leo' },
    { url: '/assets/celebrities/Michael Imperioli.jpg', name: 'Michael Imperioli' },
    { url: '/assets/celebrities/Michael J Fox.jpg', name: 'Michael J. Fox' },
    { url: '/assets/celebrities/Natalie Portman.jpg', name: 'Natalie Portman' },
    { url: '/assets/celebrities/Nicolas Cage.jpg', name: 'Nicolas Cage' },
    { url: '/assets/celebrities/Patricia Clarkson.jpg', name: 'Patricia Clarkson' },
    { url: '/assets/celebrities/Paul Giamatti.jpg', name: 'Paul Giamatti' },
    { url: '/assets/celebrities/Ray Liotta.jpg', name: 'Ray Liotta' },
    { url: '/assets/celebrities/Reese Witherspoon.jpg', name: 'Reese Witherspoon' },
    { url: '/assets/celebrities/Richard Dreyfuss.jpg', name: 'Richard Dreyfuss' },
    { url: '/assets/celebrities/Robert De Niro.jpg', name: 'Robert De Niro' },
    { url: '/assets/celebrities/Robert Downey Jr.jpg', name: 'Robert Downey Jr.' },
    { url: '/assets/celebrities/Ryan Gosling.jpg', name: 'Ryan Gosling' },
    { url: '/assets/celebrities/Sandra Bullock.jpeg', name: 'Sandra Bullock' },
    { url: '/assets/celebrities/Scarlett Johansson.jpg', name: 'Scarlett Johansson' },
    { url: '/assets/celebrities/Sean Penn.jpg', name: 'Sean Penn' },
    { url: '/assets/celebrities/Stanley Tucci.jpg', name: 'Stanley Tucci' },
    { url: '/assets/celebrities/Steve Buscemi.jpg', name: 'Steve Buscemi' },
    { url: '/assets/celebrities/Steve Carell.jpg', name: 'Steve Carell' },
    { url: '/assets/celebrities/Steve Martin.jpg', name: 'Steve Martin' },
    { url: '/assets/celebrities/Steve Schirripa.jpg', name: 'Steve Schirripa' },
    { url: '/assets/celebrities/Tom Hanks.jpg', name: 'Tom Hanks' },
    { url: '/assets/celebrities/Toni Collette.jpg', name: 'Toni Collette' },
    { url: '/assets/celebrities/Vincent Gallo.jpg', name: 'Vincent Gallo' },
]

export const speakers = [
    { url: '/assets/speakers/Aakansha Doshi.webp', name: 'Aakansha Doshi'},
    { url: '/assets/speakers/Akash Hamirwasia.webp', name: 'Akash Hamirwasia'},
    { url: '/assets/speakers/Aria Minaei.webp', name: 'Aria Minaei'},
    { url: '/assets/speakers/Arisa Fukuzaki.webp', name: 'Arisa Fukuzaki'},
    { url: '/assets/speakers/Barry Pollard.webp', name: 'Barry Pollard'},
    { url: '/assets/speakers/Brittany Joiner.webp', name: 'Brittany Joiner'},
    { url: '/assets/speakers/Bryan Hughes.webp', name: 'Bryan Hughes'},
    { url: '/assets/speakers/Caleb Porzio.webp', name: 'Caleb Porzio'},
    { url: '/assets/speakers/Cecelia Martinez.webp', name: 'Cecelia Martinez'},
    { url: '/assets/speakers/Dan Shappir.webp', name: 'Dan Shappir'},
    { url: '/assets/speakers/Elena Vilchik.webp', name: 'Elena Vilchik'},
    { url: '/assets/speakers/Elliott Johnson.webp', name: 'Elliott Johnson'},
    { url: '/assets/speakers/Emanuele Stoppa.webp', name: 'Emanuele Stoppa'},
    { url: '/assets/speakers/Erick Wendel.webp', name: 'Erick Wendel'},
    { url: '/assets/speakers/Gabriel L. Manor.webp', name: 'Gabriel L. Manor'},
    { url: '/assets/speakers/Gil Tayar.webp', name: 'Gil Tayar'},
    { url: '/assets/speakers/Hemanth HM.webp', name: 'Hemanth HM'},
    { url: '/assets/speakers/Henri Helvetica.webp', name: 'Henri Helvetica'},
    { url: '/assets/speakers/Hidde de Vries.webp', name: 'Hidde de Vries'},
    { url: '/assets/speakers/Ivan Akulov.webp', name: 'Ivan Akulov'},
    { url: '/assets/speakers/Jaxon Repp.webp', name: 'Jaxon Repp'},
    { url: '/assets/speakers/Jecelyn Yeen.webp', name: 'Jecelyn Yeen'},
    { url: '/assets/speakers/Jorrik Klijnsma.webp', name: 'Jorrik Klijnsma'},
    { url: '/assets/speakers/Juri Strumpflohner.webp', name: 'Juri Strumpflohner'},
    { url: '/assets/speakers/Kamil Ogórek.webp', name: 'Kamil Ogórek'},
    { url: '/assets/speakers/Luca Maraschi.webp', name: 'Luca Maraschi'},
    { url: '/assets/speakers/Luciano Mammino.webp', name: 'Luciano Mammino'},
    { url: '/assets/speakers/Matteo Collina.webp', name: 'Matteo Collina'},
    { url: '/assets/speakers/Maxim Salnikov.webp', name: 'Maxim Salnikov'},
    { url: '/assets/speakers/Maya Shavin.webp', name: 'Maya Shavin'},
    { url: '/assets/speakers/Michael Hablich.webp', name: 'Michael Hablich'},
    { url: '/assets/speakers/Mike Hartington.webp', name: 'Mike Hartington'},
    { url: '/assets/speakers/Minko Gechev.webp', name: 'Minko Gechev'},
    { url: '/assets/speakers/Miško Hevery.webp', name: 'Miško Hevery'},
    { url: '/assets/speakers/Nikhil Kumaran S.webp', name: 'Nikhil Kumaran S'},
    { url: '/assets/speakers/Olena Kutsenko.webp', name: 'Olena Kutsenko'},
    { url: '/assets/speakers/Phil Nash.webp', name: 'Phil Nash'},
    { url: '/assets/speakers/Rafael Gonzaga.webp', name: 'Rafael Gonzaga'},
    { url: '/assets/speakers/Robin Marx.webp', name: 'Robin Marx'},
    { url: '/assets/speakers/Ryan Carniato.webp', name: 'Ryan Carniato'},
    { url: '/assets/speakers/Sebastian Witalec.webp', name: 'Sebastian Witalec'},
    { url: '/assets/speakers/Sergey Bocharov.webp', name: 'Sergey Bocharov'},
    { url: '/assets/speakers/Tejas Kumar.webp', name: 'Tejas Kumar'},
    { url: '/assets/speakers/Tobias Koppers.webp', name: 'Tobias Koppers'},
    { url: '/assets/speakers/Wes Bos.webp', name: 'Wes Bos'},
    { url: '/assets/speakers/Will Klein.webp', name: 'Will Klein'},
    { url: '/assets/speakers/Zach Leatherman.webp', name: 'Zach Leatherman'},
    { url: '/assets/speakers/Zoe Steinkamp.webp', name: 'Zoe Steinkamp'},
]
